### ISSUE TITLE
FizzBuzzRenderer breaks SRP (Single Responsibility Principle)

### ISSUE THREAD

**Issue by lfendytw** [AliciaSJ/TW_Intro#21]
https://github.com/AliciaSJ/TW_Intro/blob/3564405a99ee5f8e8274ad83c362664ec74ab32a/src/main/TriangleHelper.java#L7

FizzBuzzRenderer contains both business logic and presentation logic. This is because the fizzbuzz does two things:
1. Decide whether to show number, or fizz, or buzz, or fizzbuzz --- this is business logic
2. Print out to console out --- this is presentation logic.

A better approach would be to just return a string, and print out in the FizzBuzz class.
this will then keep FizzBuzzRenderer only contain the business logic.

**Comment by AliciaSJ** [comment]
I have already fixed issue by changing the method type to String instead of a void. Other than breaking the rules of SRP, does mixing business and presentation logic have any other impacts on the code? Like, does it affect the overall performance and efficiency? Or is it just purely design?

Other than that, I am still pretty new to SRP. Do you have any links that I can read up on regarding this so I will understand more about SRP?

**Comment by lfendytw** [comment]
https://code.tutsplus.com/tutorials/solid-part-1-the-single-responsibility-principle--net-36074

**Comment by lfendytw** [comment]
Mixing business logic and presentation logic, in general - makes your code
resistant to change. This is due to the changes in each are usually
independent and somewhat orthogonal.

For example, if you have a tax engine that knows how to calculate tax - but
you want an ios app, android app and webpage to allow for accessing this
calculation. If the presentation logic and business logic is coupled, then
you wont have the ability to expose them through the different channels.

Its usually a design concern, not a performance / efficiency concern.

Liauw Fendy   |   +61 3 9691 6500   |   ThoughtWorks Australia
